- name: Copier les certificats SSL
  copy:
    src: "ssl/{{ item }}"
    dest: "/opt/inception/requirements/nginx/conf/{{ item }}"
    mode: '0644'
  loop:
    - "{{ domain_name }}.crt"
    - "{{ domain_name }}.nopass.key"
    - "{{ domain_name }}.ca.crt"

- name: Déployer le fichier nginx.conf
  template:
    src: nginx.conf.j2
    dest: /opt/inception/requirements/nginx/conf/nginx.conf
    mode: '0644'
