---
- name: Create project directory on server
  file:
    path: /opt/inception
    state: directory
    mode: 0755

- name: Create data directories for volumes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /opt/inception/data/mariadb
    - /opt/inception/data/wordpress

- name: Copy project files to server
  copy:
    src: "{{ role_path }}/files/"
    dest: /opt/inception/
    owner: root
    group: root
    mode: 0755

- name: Copy .env file
  copy:
    src: "{{ role_path }}/files/.env"
    dest: /opt/inception/.env
    mode: '0644'
    owner: root
    group: root

- name: Build and start containers
  command: docker compose up -d
  args:
    chdir: /opt/inception
  async: 600  # 10 minutes timeout
  poll: 10    # Check every 10 seconds
