---
- name: Restart Docker Compose in /opt/inception
  hosts: all
  become: true
  tasks:

    - name: Docker compose down
      command: docker compose down
      args:
        chdir: /opt/inception

    - name: Docker compose up
      command: docker compose up -d
      args:
        chdir: /opt/inception